services:
  # MongoDB для разработки
  mongodb:
    image: mongo:7.0
    container_name: aigull-art-mongodb-dev
    restart: always
    environment:
      MONGO_INITDB_DATABASE: aigull_art
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - aigull-dev-network

  # Web UI для MongoDB (mongo-express)
  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: aigull-art-mongo-express-dev
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - aigull-dev-network

  # Backend для разработки (с hot reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: aigull-art-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/aigull_art
      JWT_SECRET: dev-secret-key
      JWT_EXPIRE: 7d
      CORS_ORIGIN: http://localhost:3000
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/nodemon.json:/app/nodemon.json
    depends_on:
      - mongodb
    networks:
      - aigull-dev-network
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
        - action: rebuild
          path: ./backend/package.json

  # Frontend для разработки (с hot reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: aigull-art-frontend-dev
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json
      - ./frontend/index.html:/app/index.html
    depends_on:
      - backend
    networks:
      - aigull-dev-network
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend/package.json
        - action: sync
          path: ./frontend/index.html
          target: /app/index.html

volumes:
  mongodb_dev_data:

networks:
  aigull-dev-network:
    driver: bridge
